// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjMKtAhEV5czGly3kHhpAeMhbaX08Mu48',
    appId: '1:222469170141:web:75b06c3f86936573be4c34',
    messagingSenderId: '222469170141',
    projectId: 'chat-app-9dbd6',
    authDomain: 'chat-app-9dbd6.firebaseapp.com',
    storageBucket: 'chat-app-9dbd6.firebasestorage.app',
    measurementId: 'G-BZE3HDEMTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKCzQgB-Tjhn3y1EP8Weo1M6PM2kc2piY',
    appId: '1:222469170141:android:f96cb31238af844ebe4c34',
    messagingSenderId: '222469170141',
    projectId: 'chat-app-9dbd6',
    storageBucket: 'chat-app-9dbd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4zjr7TOxrIzMaN_LRs01r6S6nrAZO9nY',
    appId: '1:222469170141:ios:0902acb5e001ca9dbe4c34',
    messagingSenderId: '222469170141',
    projectId: 'chat-app-9dbd6',
    storageBucket: 'chat-app-9dbd6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4zjr7TOxrIzMaN_LRs01r6S6nrAZO9nY',
    appId: '1:222469170141:ios:0902acb5e001ca9dbe4c34',
    messagingSenderId: '222469170141',
    projectId: 'chat-app-9dbd6',
    storageBucket: 'chat-app-9dbd6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjMKtAhEV5czGly3kHhpAeMhbaX08Mu48',
    appId: '1:222469170141:web:67c8455be6a8c069be4c34',
    messagingSenderId: '222469170141',
    projectId: 'chat-app-9dbd6',
    authDomain: 'chat-app-9dbd6.firebaseapp.com',
    storageBucket: 'chat-app-9dbd6.firebasestorage.app',
    measurementId: 'G-JKEPVJNZ44',
  );
}
